### PR TITLE
frontend: Add MatomoConsentPopup

### LINKED ISSUE #1375: Add cookie disclaimer to our website
# Rationale
Matomo is using cookies so we need to add a disclaimer for users (legal reasons)

# Implementation
https://developer.matomo.org/guides/tracking-consent

# Acceptance criteria
- [x] Check what visual items need to be created (e.g. popup / toss style which has the info?
- [x] Matomo tracks users consent
- [x] Implemented matomo code only tracks once consent was given
- [x] Style of implementation is either checked or provided by @olympe-silve 
- [x] is implemented on all our pages

### PR DESCRIPTION
**Pull request by manuelwedler**
Closes #1375 

Stops Matomo tracking until the user accepts it in the pop up. Consent information is stored in Matomo.

@olympe-silve please check in the screenshot if the styling of the pop up is ok like this:
Screen Shot 2023-02-01 at 23 14 47

### CODE REVIEW

**Comment by olympe-silve** [comment]
@manuelwedler the style of the pop up is ok, but I would rather it being completely centered, with the app in the background being blurred until the user makes a decision on the CTA. As soon as that's done, the app reappears normally and useable.

**Review by GabrielBuragev — CHANGES_REQUESTED** [review]
Code wise, everything looks good. I have one minor request.

Can we also store the users selection inside `localStorage` ? That way the users that decline the consent will not have to decline again when they come to our website.
Currently, when you decline and do a page refresh you are forced to make a selection again. 
The best place to store this is probably inside the `settings` store object.

Also, check Olympe's suggestion.

**Comment by istankovic** [comment]
> Can we also store the users selection inside localStorage ? That way the users that decline the consent will not have to decline again when they come to our website.

:100: 

I am not sure about the legal aspect, but, as a user, if I consented/declined once, I would like my decision to be remembered.

**Comment by manuelwedler** [comment]
Alright, will implement the suggestions :+1: 

@olympe-silve do we want it also centered on the screen for the website?

**Review by GabrielBuragev — APPROVED** [review]
Perfect! Thanks for the edits!

**Comment by olympe-silve** [comment]
> Alright, will implement the suggestions 👍
> 
> @olympe-silve do we want it also centered on the screen for the website?

yes ! easiest option imo

**Pull request merged**
