### PR TITLE
Docs contract addresses

### PR DESCRIPTION
**Pull request by istankovic**
This PR adds a script (with a terribly long name, suggestions welcome!) to generate a doc page with contract addresses, given a deployment file. The script expects JSON on stdin and outputs rst  to be included in the docs.

The Makefile targets are updated and also CI config is changed so that whenever the mainnet deployment file is changed, the page will be regenerated and uploaded.

Example for the current deployment:
image

### CODE REVIEW

**Comment by fredo** [comment]
How will this behave now, when we have Ethereum as the base layer and as a rollup? It looks like that we would have the Headline Ethereum twice which would look confusing.

**Comment by fredo** [comment]
could you generate and post a screenshot how it looks now?

**Comment by bilbeyt** [comment]
Screenshot 2023-04-12 at 14 30 58

**Comment by bilbeyt** [comment]
> Screenshot 2023-04-12 at 14 30 58

@fredo

**Review by fredo — APPROVED** [review]
looks good

**Pull request merged**
