### PR TITLE
Release v0.1.5

### PR DESCRIPTION
**Pull request by istankovic**

### CODE REVIEW

**Review by GabrielBuragev — APPROVED** [review]
LGTM :heavy_check_mark:

**Comment by GabrielBuragev** [comment]
One question to @manuelwedler though.
Does it make sense to update the `version` property of `package.json` with the corresponding version?

I would say it doesn't make much sense since we dont have the `frontend` published as npm package. What are your thoughts?

**Comment by istankovic** [comment]
> Does it make sense to update the `version` property of `package.json` with the corresponding version?

Please note there are https://github.com/beamer-bridge/beamer/issues/505 and https://github.com/beamer-bridge/beamer/issues/473. We have been delaying work on those, but at some point it would be really nice to have them.

**Comment by manuelwedler** [comment]
> One question to @manuelwedler though. Does it make sense to update the `version` property of `package.json` with the corresponding version?
> 
> I would say it doesn't make much sense since we dont have the `frontend` published as npm package. What are your thoughts?

Since we are using the same changelog for the frontend now, I think we should follow the same versioning for it. Even if we do not publish it to npm. So yes I would start to use the `version` field now.

**Pull request merged**
