### PR TITLE
Arbitrum messengers

### LINKED ISSUE #664: Create messenger proxy for Arbitrum
Arbitrum needs its own messenger proxy. The function signature is `sendL1FundedContractTransaction(uint256 maxGas, uint256 gasPriceBid, address destAddr, bytes data)`.

https://developer.offchainlabs.com/docs/sol_contract_docs/md_docs/arb-bridge-eth/bridge/inbox

### PR DESCRIPTION
**Pull request by istankovic**
Closes #664.

### CODE REVIEW

**Comment by fredo** [comment]
looks good! 
One nitpick: Can't we just use the optimism vendor contracts and get rid of [ICrossDomainMessenger.sol](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/chains/optimism/ICrossDomainMessenger.sol) ?

**Comment by istankovic** [comment]
> looks good! One nitpick: Can't we just use the optimism vendor contracts and get rid of [ICrossDomainMessenger.sol](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/chains/optimism/ICrossDomainMessenger.sol) ?

Absolutely, I was planning to do so, just not within this PR. But I can also include it here if you think that's alright.

**Comment by istankovic** [comment]
> looks good! One nitpick: Can't we just use the optimism vendor contracts and get rid of [ICrossDomainMessenger.sol](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/chains/optimism/ICrossDomainMessenger.sol) ?

Done.

**Review by fredo — APPROVED** [review]
awesome!

**Pull request merged**
