### PR TITLE
frontend: Left align all form fields

### LINKED ISSUE #526: Target rollup and Address place holder text should be alligned
## Description
Current, the placeholder text "Target Rollup" is left aligned, and the text "Address" is right aligned. This should not be the case and they should both be left aligned to be consistent. See scrot:
Screenshot 2022-04-07 at 10 25 54

## Acceptance criteria
All placeholder text is left aligned

### PR DESCRIPTION
**Pull request by manuelwedler**
Close #526 

Fixes the text of all form fields to be aligned on the same side. I decided for the right side as it is in Olympe's design.

### CODE REVIEW

**Comment by nekhaly** [comment]
Aligning the select boxes text right looks very weird to me! Also taking into consideration that there will be an icon for each item in the future, where it should be?
Forget all of this if @olympe-silve has agreed on that already!
image

**Comment by nekhaly** [comment]
@manuelwedler 
I have just talked with @olympe-silve and the decision is to align all fields (inputs and selectors) to left instead to avoid the issue of icons' place in the future!

**Review by nekhaly — CHANGES_REQUESTED** [review]
Check my comment!

**Comment by manuelwedler** [comment]
Ok, I made the changes. Please have another look.

**Review by weilbith — APPROVED** [review]
I tested it again and it works as expected: all placeholders and content are aligned to the left. Good job. 👍🏾

**Comment by manuelwedler** [comment]
@nekhaly Seems like I need an approval from you for being able to merge.

**Review by nekhaly — APPROVED** [review]
Here it is! Github became very strict nowadays :)

**Pull request merged**
