### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Review by istankovic — APPROVED** [review]
Looking good, thanks for the contribution!

**Comment by istankovic** [comment]
@omahs could you please rebase this on top of latest `main`? There was a fix for the CI failures today.

**Comment by omahs** [comment]
Hey @istankovic, just did 👍

**Comment by omahs** [comment]
@istankovic I'll close this and start again with the same PR from main. (it's easier for me hope you won't mind)

**Comment by omahs** [comment]
@istankovic Here's the new PR: https://github.com/beamer-bridge/beamer/pull/1193

**Pull request closed without merging**
