### PR TITLE
relayer: use variables for replace in sed

### PR DESCRIPTION
**Pull request by compojoom**
I was too fast to merge this PR https://github.com/beamer-bridge/beamer/pull/1976

Addressed @istankovic comments here.

### CODE REVIEW

**Review by istankovic — APPROVED** [review]
Looks good.

**Comment by istankovic** [comment]
@compojoom could you please rebase on top of latest `main`, I pushed a fix for the lint failure.

**Comment by istankovic** [comment]
@compojoom I just noticed your commit messages are prefixed with `relayer:`, which seems wrong as we are not modifiying the relayer here. Could you please change them?

**Comment by compojoom** [comment]
ok, so what? docker? I'm adding relayer as those e2e tests are for the relayer?

**Comment by istankovic** [comment]
> ok, so what? docker? 

Yeah, I think most people use just `docker:` for that part.

> I'm adding relayer as those e2e tests are for the relayer?

Well, we do test the relayer, but also almost everything else (this is where the `e2e == end-to-end` part comes from). So it's not just about the relayer. (Generally, relayer changes are prefixed with `relayer:` and touch stuff under `relayer/`.)

**Comment by compojoom** [comment]
k, done

**Pull request merged**
