### PR TITLE
frontend: add GPL license

### PR DESCRIPTION
**Pull request by GabrielBuragev**
The frontend had no license specified in its `package.json`.

### CODE REVIEW

**Comment by istankovic** [comment]
Are we ok with GPL?
What licenses are used by our dependencies?
Did you check `NODE_ENV=production yarn licenses list`?

**Comment by andfletcher** [comment]
MIT and GPL are fine for me.

**Comment by andfletcher** [comment]
Also everything we do should have a licens

**Review by istankovic — APPROVED** [review]

**Comment by istankovic** [comment]
@GabrielBuragev could you please check whether we need to do the same for relayer?

**Comment by GabrielBuragev** [comment]
I was thinking if we use the GPL for the relayer as well. What do you guys think?

**Comment by istankovic** [comment]
> I was thinking if we use the GPL for the relayer as well. What do you guys think?

Yes, makes sense to use the same for both.

**Pull request merged**
